/* eslint-disable no-underscore-dangle */
import { FlatCompat } from '@eslint/eslintrc';
import babelParser from '@babel/eslint-parser';
import { fileURLToPath } from 'node:url';
import globals from 'globals';
import js from '@eslint/js';
import path from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all
});

export default [
  ...compat.extends('eslint:recommended'),
  {
    languageOptions: {
      globals: {
        ...globals.browser
      },
      parser: babelParser,
      ecmaVersion: 'latest',
      sourceType: 'module'
    },
    rules: {
      'accessor-pairs': 'error',
      'array-bracket-newline': 'error',
      'array-bracket-spacing': ['error', 'never'],
      'array-callback-return': 'error',
      'array-element-newline': 'off',
      'arrow-body-style': 'error',
      'arrow-parens': 'error',
      'arrow-spacing': 'error',
      'block-scoped-var': 'error',
      'block-spacing': ['error', 'always'],
      camelcase: 'error',
      'capitalized-comments': ['error', 'never'],
      'class-methods-use-this': 'off',
      'comma-dangle': 'error',
      'comma-spacing': 'off',
      'comma-style': ['error', 'last'],
      complexity: 'off',
      'computed-property-spacing': 'error',
      'consistent-return': 'off',
      'consistent-this': 'error',
      curly: 'off',
      'default-case': 'error',
      'default-case-last': 'error',
      'default-param-last': 'error',
      'dot-location': ['error', 'property'],
      'dot-notation': 'error',
      'eol-last': 'off',
      eqeqeq: 'off',
      'func-call-spacing': 'error',
      'func-name-matching': 'error',
      'func-names': 'off',
      'func-style': 'off',
      'function-paren-newline': 'off',
      'generator-star-spacing': 'error',
      'grouped-accessor-pairs': 'error',
      'guard-for-in': 'error',
      'id-denylist': 'error',
      'id-length': 'off',
      'id-match': 'error',
      'implicit-arrow-linebreak': 'error',
      indent: 'off',
      'init-declarations': 'error',
      'jsx-quotes': 'error',
      'key-spacing': 'off',
      'keyword-spacing': 'off',
      'line-comment-position': 'error',
      'linebreak-style': ['error', 'unix'],
      'lines-around-comment': 'error',
      'lines-between-class-members': 'error',
      'max-classes-per-file': 'error',
      'max-depth': 'error',
      'max-len': 'off',
      'max-lines': 'error',
      'max-lines-per-function': 'off',
      'max-nested-callbacks': 'error',
      'max-params': ["error", 5],
      'max-statements': 'off',
      'max-statements-per-line': 'off',
      'multiline-comment-style': ['error', 'starred-block'],
      'multiline-ternary': 'off',
      'new-cap': 'off',
      'new-parens': 'error',
      'newline-per-chained-call': 'error',
      'no-alert': 'error',
      'no-array-constructor': 'error',
      'no-await-in-loop': 'error',
      'no-bitwise': 'error',
      'no-caller': 'error',
      'no-confusing-arrow': 'error',
      'no-console': [
        'error', {
        allow: ['warn', 'error']
        }
      ],
      'no-constructor-return': 'off',
      'no-continue': 'error',
      'no-div-regex': 'error',
      'no-duplicate-imports': 'error',
      'no-else-return': 'off',
      'no-empty-function': 'error',
      'no-eq-null': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'off',
      'no-extra-label': 'error',
      'no-extra-parens': 'off',
      'no-floating-decimal': 'error',
      'no-implicit-coercion': 'error',
      'no-implicit-globals': 'off',
      'no-implied-eval': 'error',
      'no-inline-comments': 'error',
      'no-inner-declarations': ['error', 'functions'],
      'no-invalid-this': 'error',
      'no-iterator': 'error',
      'no-label-var': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-lonely-if': 'error',
      'no-loop-func': 'error',
      'no-loss-of-precision': 'error',
      'no-magic-numbers': 'off',
      'no-mixed-operators': 'error',
      'no-multi-assign': 'error',
      'no-multi-spaces': 'error',
      'no-multi-str': 'error',
      'no-multiple-empty-lines': 'error',
      'no-negated-condition': 'error',
      'no-nested-ternary': 'error',
      'no-new': 'off',
      'no-new-func': 'error',
      'no-new-object': 'error',
      'no-new-wrappers': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': 'error',
      'no-plusplus': [
        'error', {
          allowForLoopAfterthoughts: true
        }
      ],
      'no-promise-executor-return': 'error',
      'no-proto': 'error',
      'no-restricted-exports': 'error',
      'no-restricted-globals': 'error',
      'no-restricted-imports': 'error',
      'no-restricted-properties': 'error',
      'no-restricted-syntax': 'error',
      'no-return-assign': 'error',
      'no-return-await': 'error',
      'no-script-url': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-shadow': 'error',
      'no-tabs': 'off',
      'no-template-curly-in-string': 'error',
      'no-ternary': 'off',
      'no-throw-literal': 'error',
      'no-trailing-spaces': 'error',
      'no-undef-init': 'error',
      'no-undefined': 'off',
      'no-underscore-dangle': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unneeded-ternary': 'error',
      'no-unreachable-loop': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-expressions': 'off',
      'no-use-before-define': 'off',
      'no-useless-backreference': 'error',
      'no-useless-call': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-concat': 'error',
      'no-useless-constructor': 'error',
      'no-useless-rename': 'error',
      'no-useless-return': 'error',
      'no-var': 'off',
      'no-void': 'error',
      'no-warning-comments': 'error',
      'no-whitespace-before-property': 'error',
      'nonblock-statement-body-position': 'error',
      'object-curly-newline': 'error',
      'object-curly-spacing': 'off',
      'object-shorthand': 'error',
      'one-var': 'off',
      'one-var-declaration-per-line': 'error',
      'operator-assignment': ['error', 'always'],
      'operator-linebreak': 'error',
      'padded-blocks': 'off',
      'padding-line-between-statements': 'error',
      'prefer-arrow-callback': 'off',
      'prefer-const': 'error',
      'prefer-destructuring': 'off',
      'prefer-exponentiation-operator': 'error',
      'prefer-named-capture-group': 'off',
      'prefer-numeric-literals': 'error',
      'prefer-object-spread': 'error',
      'prefer-promise-reject-errors': 'error',
      'prefer-regex-literals': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'off',
      'quote-props': 'off',
      quotes: 'off',
      radix: ['error', 'as-needed'],
      'require-atomic-updates': 'error',
      'require-await': 'error',
      'require-unicode-regexp': 'off',
      'rest-spread-spacing': 'error',
      semi: 'off',
      'semi-spacing': [
        'error', {
          after: true,
          before: false
        }
      ],
      'semi-style': ['error', 'last'],
      'sort-imports': 'error',
      'sort-keys': 'off',
      'sort-vars': 'off',
      'space-before-blocks': 'off',
      'space-before-function-paren': 'off',
      'space-in-parens': 'off',
      'space-infix-ops': 'error',
      'space-unary-ops': 'error',
      'spaced-comment': ['error', 'always'],
      strict: ['error', 'never'],
      'switch-colon-spacing': 'error',
      'symbol-description': 'error',
      'template-curly-spacing': 'error',
      'template-tag-spacing': 'error',
      'unicode-bom': ['error', 'never'],
      'vars-on-top': 'off',
      'wrap-iife': 'error',
      'wrap-regex': 'error',
      'yield-star-spacing': 'error',
      yoda: ['error', 'never']
    }
  }
];
